version: "3.8"
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
    command: npm start
